spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_step02_order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234

    jpa:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: true