spring:
  application:
    name: order-service

# 서비스 디스커버리 설정(localhost:8081대신 payment-service라는 이름으로 결제 서비스를 탐색)
# payment-service의 이름은 spring.application.name을 기반으로 함
service:
  payment:
    url: http://payment-service/payments

server:
  port: 8080

# cloud config 테스트용 설정 값
custom:
  message: "초기 메시지 - DEV 환경입니다"
  version: "1.0.0"